# Generated by Django 4.0.2 on 2022-04-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_profile_remove_comment_date_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fiverr_url',
            new_name='fiverr',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_url',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter_url',
            new_name='twitter',
        ),
    ]
